grep -r "GSOL_INTERFACE_CURVATURE_GEOMETRIC:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_CURVATURE_GEOMETRIC
grep -r "GSOL_INTERFACE_CURVATURE:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_CURVATURE
grep -r "GSOL_INTERFACE_CURVATURE_SQUARED:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_CURVATURE_SQUARED
grep -r "GSOL_INTERFACE_PERIMETER:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_PERIMETER
