grep -r "GSOL_INTERFACE_CURVATURE_BEAM_LAGRANGE:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_CURVATURE_BEAM_LAGRANGE
grep -r "GSOL_INTERFACE_PERIMETER:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_PERIMETER
