grep -r "GSOL_INTERFACE_PERIMETER:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_PERIMETER
grep -r "GSOL_NORMAL_INTERFACE_MEAN_CURVATURE:" beam2D.out | awk '{print $2;}' > GSOL_NORMAL_INTERFACE_MEAN_CURVATURE
grep -r "GSOL_INTERFACE_CURVATURE:" beam2D.out | awk '{print $2;}' > GSOL_INTERFACE_CURVATURE

